services:
  db:
    image: postgres:16.1
    container_name: shareit
    ports:
      - "5435:5432"
    volumes:
      - .\volumes\postgres\shareit:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

